version: "3"

services:
    # web:
    #     container_name: linguaLiftApp
    #     build: ./Web
    #     environment:
    #         MYSQL_DATABASE: lingua_lift
    #         MYSQL_USER: root
    #         MYSQL_PASSWORD: root
    #         MYSQL_HOST: mysql
    #     ports:
    #         - "5000:3000"
    #     depends_on:
    #         - mysql
    #     restart: on-failure
    #     volumes:
    #         - ./Web:/usr/src/app
    mysql:
        container_name: lingualiftdatabase
        build: ./Database
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: lingua_lift
        restart: always
